name = "FITSIO"
uuid = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
version = "0.17.5"

[workspace]
projects = ["test", "docs"]

[deps]
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[weakdeps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extensions]
FITSIOTablesExt = "Tables"

[compat]
CFITSIO = "1.7.0"
Printf = "<0.0.1, 1"
Reexport = "0.2, 1.0"
Tables = "1"
julia = "1.10"
