name = "FITSIO"
uuid = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
version = "0.16.4"

[deps]
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CFITSIO = "1"
Reexport = "0.2"
julia = "1.3"
Tables = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
