name = "FITSIO"
uuid = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
version = "0.17.5"

[deps]
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extensions]
FITSIOTablesExt = "Tables"

[compat]
Aqua = "0.8"
CFITSIO = "1.7.0"
OrderedCollections = "1"
Printf = "<0.0.1, 1"
Random = "<0.0.1, 1"
Reexport = "0.2, 1.0"
Tables = "1"
Test = "<0.0.1, 1"
julia = "1.3"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "OrderedCollections", "Random", "Tables", "Test"]
